*--- DEFINICIONES DE TECLAS
#DEFINE KEY_TECLA_HOME   1
#DEFINE KEY_PAGE_DOWN    3
#DEFINE KEY_FLECHA_DER   4
#DEFINE KEY_FLECHA_ARR   5
#DEFINE KEY_TECLA_END    6
#DEFINE KEY_TAB          9
#DEFINE KEY_LINEFEED    10
#DEFINE KEY_ENTER       13
#DEFINE KEY_PAGE_UP     18
#DEFINE KEY_FLECHA_IZQ  19
#DEFINE KEY_CTRL_W      23
#DEFINE KEY_FLECHA_ABA  24
#DEFINE KEY_ESC         27
#DEFINE KEY_ESPACIO     32
#DEFINE KEY_BACKSPACE  127

*--- COLORES UTILIZADOS (CLR=color, D=deshabilitado, H=Habilitado)
#DEFINE CLR_Fondo_Boton_Main_H             RGB(  0,   0,   0)
#DEFINE CLR_Fondo_Boton_Main_D             RGB(255, 255, 255)

#DEFINE CLR_Fondo_Input_Total_Error        RGB(255,   0,   0)
#DEFINE CLR_Texto_Input_Total_Error        RGB(255, 255, 255)

#DEFINE CLR_Fondo_Input_Total_OK           RGB(255, 255, 128)
#DEFINE CLR_Texto_Input_Total_OK           RGB(  0,   0, 128)

#DEFINE CLR_Fondo_Grilla_D                 RGB(240, 240, 240)
#DEFINE CLR_Texto_Grilla_D                 RGB(  0,   0,   0)

#DEFINE CLR_Fondo_Grilla_H                 RGB(255, 255, 192)
#DEFINE CLR_Texto_Grilla_H                 RGB(  0,   0, 255)

#DEFINE CLR_Fondo_Grilla_Fila_Impar        RGB(240, 240, 240)
#DEFINE CLR_Fondo_Grilla_Fila_Par          RGB(192, 192, 192)

#DEFINE CLR_Fondo_Header                   RGB(176, 176,  96)
#DEFINE CLR_Texto_Header                   RGB( 32,  32,  32)

#DEFINE CLR_Fondo_Incremental              RGB( 64,  64,  32)
#DEFINE CLR_Texto_Incremental              RGB(255, 255, 128)

#DEFINE CLR_Fondo_Label_Titulo_Activado    RGB(  0,   0, 192)
#DEFINE CLR_Texto_Label_Titulo_Activado    RGB(255, 255, 255)

#DEFINE CLR_Fondo_Label_Titulo_Desactivado RGB(176, 176, 176)
#DEFINE CLR_Texto_Label_Titulo_Desactivado RGB( 32,  32,  32)

#DEFINE CLR_Fondo_Pestana                  RGB(255, 128,  64)
#DEFINE CLR_Texto_Pestana                  RGB(  0,   0, 255)

*--- CAJA DE MENSAJES. CM=Caja de Mensaje
#DEFINE CM_BTN_OK                           0
#DEFINE CM_BTN_OK_CANCEL                    1
#DEFINE CM_BTN_ABORTAR_REINTENTAR_IGNORAR   2
#DEFINE CM_BTN_SI_NO_CANCELAR               3
#DEFINE CM_BTN_SI_NO                        4
#DEFINE CM_BTN_REINTENTAR_CANCELAR          5
#DEFINE CM_ICONO_STOP                      16
#DEFINE CM_ICONO_PREGUNTA                  32
#DEFINE CM_ICONO_EXCLAMACION               48
#DEFINE CM_ICONO_INFORMACION               64
#DEFINE CM_POR_DEFECTO_BOTON1               0
#DEFINE CM_POR_DEFECTO_BOTON2             256
#DEFINE CM_POR_DEFECTO_BOTON3             512
#DEFINE CM_ARRIBA_TODOS                  8192
#DEFINE CM_VALOR_RETORNO_ES_OK              1
#DEFINE CM_VALOR_RETORNO_ES_CANCELAR        2
#DEFINE CM_VALOR_RETORNO_ES_ABORTAR         3
#DEFINE CM_VALOR_RETORNO_ES_REINTENTAR      4
#DEFINE CM_VALOR_RETORNO_ES_IGNORAR         5
#DEFINE CM_VALOR_RETORNO_ES_SI              6
#DEFINE CM_VALOR_RETORNO_ES_NO              7

*--- Base64
#DEFINE BASE64_CODIFICAR   13
#DEFINE BASE64_DECODIFICAR 14

*--- ¿Existe una propiedad, método, o evento?
#DEFINE PEM_EXISTENTE 5


